'$schema' = 'https://starship.rs/config-schema.json'

format = """
[](fg:pink)\
[🧑🏻‍💻 ](bg:pink)\

[](fg:pink bg:peach)\
$directory\

[](fg:peach bg:yellow)\
$git_branch\
$git_status\

[](fg:yellow bg:green)\
$nodejs\

[](fg:green bg:sapphire)\
$battery\

[](fg:sapphire bg:lavender)\
$time\
[ ](fg:lavender)\

$cmd_duration\
\n$character"""

palette = 'catppuccin_mocha'

[palettes.catppuccin_mocha]
rosewater = '#f5e0dc'
flamingo = '#f2cdcd'
pink = '#f5c2e7'
mauve = '#cba6f7'
red = '#f38ba8'
maroon = '#eba0ac'
peach = '#fab387'
yellow = '#f9e2af'
green = '#a6e3a1'
teal = '#94e2d5'
sky = '#89dceb'
sapphire = '#74c7ec'
blue = '#89b4fa'
lavender = '#b4befe'
text = '#cdd6f4'
subtext1 = '#bac2de'
subtext0 = '#a6adc8'
overlay2 = '#9399b2'
overlay1 = '#7f849c'
overlay0 = '#6c7086'
surface2 = '#585b70'
surface1 = '#45475a'
surface0 = '#313244'
base = '#1e1e2e'
mantle = '#181825'
crust = '#11111b'

[directory]
format = '[ $path ]($style)'
style = 'fg:crust bg:peach'
truncation_length = 0
truncate_to_repo = false

[git_branch]
symbol = ''
format = '[ $symbol $branch ]($style)'
style = 'fg:crust bg:yellow'

[git_status]
format = '[$all_status$ahead_behind ]($style)'
style = 'fg:crust bg:yellow'
stashed = '⚑'

[nodejs]
symbol = ''
format = '[ $symbol $version ]($style)'
style = 'fg:crust bg:green'

[battery]
format = '[ $symbol$percentage ]($style)'
[[battery.display]]
threshold = 30
style = 'fg:crust bg:sapphire'

[time]
disabled = false
time_format = '%R'
format = '[  $time ]($style)'
style = 'fg:crust bg:lavender'

[cmd_duration]
disabled = false
format = ' in $duration '
style = 'bg:lavender'
show_milliseconds = true
show_notifications = true
min_time_to_notify = 45000

[character]
disabled = false
success_symbol = '[❯](bold fg:green)'
error_symbol = '[❯](bold fg:red)'
vimcmd_symbol = '[❮](bold fg:green)'
vimcmd_replace_one_symbol = '[❮](bold fg:lavender)'
vimcmd_replace_symbol = '[❮](bold fg:lavender)'
vimcmd_visual_symbol = '[❮](bold fg:yellow)'
